#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.0.0.1:8848
#  application:
#    name: gulimall-gateway
#server:
#  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_router
          uri: https://www.baidu.com
          predicates:
            - Query=url,qq