spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_router
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: admin_router
          uri: lb://renren-fast
          predicates:
             - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/renren-fast$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            ## 重复响应头去重
  ## 前端项目, api/
##  http://localhost:88/api/captcha.jpg http://localhost:8080/renren-fast/captcha.jpg  默认先路由到renren-fast服务模块 设置了filters后会把/api替换成/renren-fast
  application:
    name: gulimall-gateway
server:
  port: 88